/* Copyright (c) Microsoft Corporation.
   Licensed under the MIT License. */

#ifndef _VT_CONFIG_CS_H
#define _VT_CONFIG_CS_H

#define VT_CS_NUM_TRUTHS 10
#define VT_CS_ACRFFT_MAX_PEAKS 3
#define VT_CS_MAX_SIGNATURES 5
#define VT_CS_SAMPLE_LENGTH 128
#define VT_CS_FFT_LENGTH VT_CS_SAMPLE_LENGTH/2
#define VT_CS_FFT_RANGES_DIVISOR 2
#define VT_CS_NUM_EXP_RANGES 5
#define VT_CS_ADC_MIN_SAMPLING_FREQ 100.0f
#define VT_CS_ADC_MAX_SAMPLING_FREQ 5000
#define VT_CS_ADC_CURR_GAIN 50
#define VT_CS_MAX_SIGNATURES 5
#define VT_CS_MULTISAMPLING_MAX_SIGNATURES 10
#define VT_CS_MAX_TEST_FREQUENCIES 10  
#if VT_CS_MAX_SIGNATURES > VT_CS_MAX_TEST_FREQUENCIES
   #undef VT_CS_MAX_TEST_FREQUENCIES
   #define VT_CS_MAX_TEST_FREQUENCIES VT_CS_MAX_SIGNATURES
#endif
#define VT_CS_MAX_HARMONICS_REMOVAL 6
#define VT_CS_AUTO_CORRELATION_LAG 32
#define VT_CS_MIN_CORRELATION 0.4f
#define VT_CS_CALIB_MINIMUM_CYCLES 4
#define VT_CS_AVG_SIGNATURE_REPEATABILITY_TEST 3
#define VT_CS_MAX_AVG_CURR_DRIFT 5//CHANGED THIS FROM 50 TO 30
#define VT_CS_MAX_SIGNATURE_DRIFT 50
#define VT_CS_NON_REPEATING_SIGNATURE 0x01
#define VT_CS_REPEATING_SIGNATURE 0x02

#endif