name: Build Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: .

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install ninja-build

      - name: Build project
        run: |
          cmake -Bbuild -GNinja -DVT_UNIT_TESTING=ON
          cmake --build build

      - name: Run unit tests
        run: |
          cd build
          ctest -V

      - name: Output code coverage
        run: |
          ctest -V -S ctest_coverage

