name: Build Core

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: .

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: sudo apt-get install ninja-build

      - name: Install coverage utility
        run: pip install gcovr

      - name: Build coverage target for gcov
        run: |
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Coverage -DVT_UNIT_TESTING=ON -DVT_CODE_COVERAGE=ON
          cmake --build build --verbose

      - name: Run unit tests
        run: |
          cd build/tests
          ctest -V

      - name: Generate code coverage
        run: |
          cmake --build build --target vt_core_test_coverage

      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/vt_core_test_coverage.xml
          flags: unittests
          name: Unit testing coverage
          fail_ci_if_error: true
