name: Build Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: tests/core

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install ninja cmocka

      - name: Build project
        run: |
          cmake -Bbuild -GNinja -DUNIT_TESTING=ON
          cmake --build build

      - name: Run unit tests
        run: ctest
